version: "3.8"
services:
  pg-docker:
    image: postgres:15-alpine
    env_file:
      - .env.local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: express_redux
    ports:
      - 6432:5432
    volumes:
      - docker-demo_pg-data:/var/lib/postgresql/data
      - ./db:/tmp/db
   
volumes:
    docker-demo_pg-data:
      external: true
